name: Workflow AlejandroBolano

on:
  push:
    branches:
      - dev
      - master
    paths-ignore:
      - 'src/environments/**'

  pull_request:
    branches:
      - master
    paths-ignore:
      - 'src/environments/**'
